Feature/cloud fn readme update
disarm-platform/dhis2-integration pull request #1
Opened 2020-02-17 12:42 UTC by manqobasukati

2020-02-17 12:44 UTC, manqobasukati commented
![](https://github.trello.services/images/mini-trello-icon.png) [upgrade integration code](https://trello.com/c/ev0FG1Xt/109-upgrade-integration-code)

2020-02-17 12:52 UTC, onlyjsmith requested changes

2020-02-17 12:52 UTC, onlyjsmith commented on 2020-disarm-api/cloud-function/README.md
> +    - `DHIS_AUTH` to `Base <base64_string>`
Are you sure it's `Base` here?

2020-02-18 08:31 UTC, manqobasukati commented on 2020-disarm-api/cloud-function/README.md
> +    - `DHIS_AUTH` to `Base <base64_string>`
done

2020-02-18 08:58 UTC, onlyjsmith approved these changes

2020-02-18 08:58 UTC, merged